<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>ModernWigiDash.Service</RootNamespace>
    <AssemblyName>ModernWigiDash.Service.Contracts</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CoreWCF.Primitives" Version="1.9.1" />
    <PackageReference Include="System.ServiceModel.Http" Version="10.0.652802" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ModernWigiDash.Sdk\ModernWigiDash.Sdk.csproj" />
  </ItemGroup>

</Project>
