# Generates ModernWigiDash.Widgets/GriddyIconPaths.g.cs from the Griddy Icons
# repository (MIT licensed) and writes LICENSE-GriddyIcons.txt next to the
# Widgets project. Run from the repository root. The generated file and
# license are committed so builds and tests stay fully offline.
#
# Usage:
#   powershell -ExecutionPolicy Bypass -File scripts\griddy-generate.ps1 [-RepoPath <path>]
#
# If -RepoPath is omitted, the script clones github.com/griddy-icons/griddy-icons
# (shallow) into the temp directory under $env:TEMP\opencode\griddy-icons.

param(
    [string]$RepoPath = ""
)

$ErrorActionPreference = 'Stop'
$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$widgetsDir = Join-Path $repoRoot 'ModernWigiDash.Widgets'
$outFile = Join-Path $widgetsDir 'GriddyIconPaths.g.cs'
$licenseFile = Join-Path $widgetsDir 'LICENSE-GriddyIcons.txt'
$sourceDir = ''

if ($RepoPath) {
    $sourceDir = Join-Path $RepoPath 'icons-src\regular'
    if (-not (Test-Path -LiteralPath $sourceDir)) { throw "Regular icons folder not found under -RepoPath: $sourceDir" }
} else {
    $tmp = Join-Path $env:TEMP 'opencode\griddy-icons'
    if (-not (Test-Path -LiteralPath (Join-Path $tmp 'icons-src\regular'))) {
        Write-Host "Cloning Griddy Icons (shallow) into $tmp ..."
        if (Test-Path -LiteralPath $tmp) { Remove-Item -Recurse -Force -LiteralPath $tmp }
        git clone --depth 1 https://github.com/griddy-icons/griddy-icons $tmp 2>&1 | Out-Null
        if (-not $?) { throw 'git clone failed.' }
    }
    $sourceDir = Join-Path $tmp 'icons-src\regular'
}

$svgs = Get-ChildItem -LiteralPath $sourceDir -Filter *.svg
if (($svgs | Measure-Object).Count -lt 1000) { throw "Only $(($svgs | Measure-Object).Count) SVGs found; expected >= 1000." }

$entries = [System.Collections.Generic.List[object]]::new()
$seen = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)
$skipped = [System.Collections.Generic.List[string]]::new()

foreach ($svg in $svgs) {
    $name = [System.IO.Path]::GetFileNameWithoutExtension($svg.Name)
    $content = Get-Content -LiteralPath $svg.FullName -Raw
    # Clip paths are never painted, so drop their (full-box) rects before extraction.
    $content = $content -replace '(?s)<clipPath[^>]*>.*?</clipPath>', ''
    # \b prevents matching the trailing "d" of attributes like id="...".
    $dMatches = [regex]::Matches($content, '\bd="([^"]*)"')
    if ($dMatches.Count -eq 0) {
        $skipped.Add($name)
        continue
    }
    $pathData = ($dMatches | ForEach-Object { $_.Groups[1].Value }) -join ' '
    if ([string]::IsNullOrWhiteSpace($pathData) -or -not $seen.Add($name)) {
        $skipped.Add($name)
        continue
    }
    $entries.Add([pscustomobject]@{ Name = $name; PathData = $pathData })
}

if ($entries.Count -lt 1000) { throw "Only $($entries.Count) icons resolved; expected >= 1000. Skipped: $($skipped -join ', ')" }

$lines = foreach ($entry in $entries) {
    $escaped = $entry.PathData.Replace('\', '\\').Replace('"', '\"')
    '        ["{0}"] = "{1}",' -f $entry.Name, $escaped
}

$content = @"
// <auto-generated> Generated by scripts\griddy-generate.ps1 from the Griddy Icons
// repository (github.com/griddy-icons/griddy-icons, MIT). Do not edit by hand.
namespace ModernWigiDash.Widgets;

public static partial class GriddyIconPaths
{
    public static readonly System.Collections.Generic.IReadOnlyDictionary<string, string> Map =
        new System.Collections.Generic.Dictionary<string, string>(System.StringComparer.OrdinalIgnoreCase)
        {
$($lines -join "`n")
        };
}
"@

Set-Content -LiteralPath $outFile -Value $content -Encoding UTF8

$license = @'
MIT License

Copyright (c) 2025 Griddy Icons

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
'@

Set-Content -LiteralPath $licenseFile -Value $license -Encoding UTF8

Write-Host "Resolved $($entries.Count) icons -> $outFile"
if ($skipped.Count -gt 0) { Write-Warning "Skipped $($skipped.Count) icons: $($skipped -join ', ')" }
